services:
  membershipplanmanagement-api:
    image: ${DOCKER_REGISTRY-}membershipplanmanagement-api
    build:
      context: .
      dockerfile: MembershipPlanManagement/Api/Dockerfile
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5200
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: MembershipPlanManagementDb